### ISSUE TITLE
Customization?

### ISSUE THREAD

**Issue by vbeffara** [jbree/ide-clangd#1]
Hi,

Looking forward to the IDE features in atom for C++, but there would need to be some way to customize the behavior of clangd for it to be useful. Include paths are workable via environment variables (set CPATH to the list of locations), but is there a way to set general compilation flags in the protocol?

**Comment by vbeffara** [comment]
... something like this seems to work, I have no clue how to expose it in configuration. But now I can use the IDE :-)

https://github.com/vbeffara/atom-languageclient/commit/016744dfd85cf7b3922d540b4b48b8ee6dd4212b

**Comment by jbree** [comment]
Clangd supports the compile_commands.json file to specify compile commands (not sure if in prebuilt binary yet). CMake can generate these files, or they’re pretty simple to specify yourself(but tedious). Try googling for the format. may need to restart atom to make it pick up the file. eventually will add support for specifying custom path to file.

**Comment by vbeffara** [comment]
Aha, great, thanks!

In fact I had such a file already, and it is indeed recognized, but I didn't realize it at first because I was only opening header files. Looking online, I see that header files are not mentioned in the compile_commands.json and that it is a common complaint. 

What's your advice for headers?

**Comment by rwols** [comment]
@vbeffara you can try using compdb: https://github.com/Sarcasm/compdb/issues/2

**Comment by jbree** [comment]
Another option, which I just updated the readme to reflect, is a compile_flags.txt file.

[more info here](https://clang.llvm.org/docs/JSONCompilationDatabase.html#alternatives)
