### ISSUE TITLE
Unable to start Clangd language server

### ISSUE THREAD

**Issue by boodii0308** [jbree/ide-clangd#12]
Tried to spawn process using executable /usr/bin/clangd, which does not exist. Ensure you have correctly configured the path to Clangd in the package settings.

its happening all the time. pls help me

**Comment by jbree** [comment]
One of the prereqs for this plugin is to have the clangd executable installed. See the readme for a link.

**Comment by lvcargnini** [comment]
I am having the same issue. However, my clangd is on /usr/local/bin/clangd. How can we set-up the search path for this plugin, without creating symbolic links on the system?

**Comment by jbree** [comment]
Take a look at the plugin settings. If the `clangd` executable is not in a folder on your $PATH, you may manually specify the full path to the executable.
