### ISSUE TITLE
custom location of clangd

### ISSUE THREAD

**Issue by davydden** [jbree/ide-clangd#4]
I trying to make `ide` work with c++, `ide-cpp` does not work for me, but I can't use `ide-clangd` either as I need a way to provide a custom path to `clangd`. Is it possible to add this?

**Comment by jbree** [comment]
Okay, I've released a new version. There is now a field on the options page to provide the path to your clangd executable. I recommend you use the version of clangd which comes with the recently released LLVM 6.0.

Please let me know if this works for you.

**Comment by davydden** [comment]
@jbree thank you very much for the swift reply, i will give it a try right away

**Comment by davydden** [comment]
p.s. some version strings might be missing as Atom says

> Restart Atom to complete update of ide-clangd
> 0.1.2 -> undefined
