### ISSUE TITLE
compile_commands.json

### ISSUE THREAD

**Issue by BigfootN** [jbree/ide-clangd#7]
Hello,

I am trying to make this package work. Unfortunately, I am under the impression that it doesn't take into account the `compile_commands.json` (generated from cmake) file located at the root of my project. It shows errors where there shoudn't be any.

My clang version is `6.0.0`.

Thank you very much in advance.

**Comment by jbree** [comment]
It should take compile_commands.json into account, but unfortunately only at the time of launch. need to restart atom for it to pick up changes.

**Comment by jbree** [comment]
Would you mind creating a minimal test project as an example to confirm this behavior, and send me a copy to see if I can reproduce? Also, your `apm list` and platform/version info.

**Comment by BigfootN** [comment]
Hello,

Thank you very much for your support.

So I noticed that the include directories seem only to be taken into account with the `cpp` files not with the `hpp` files, or headers. If I create for example the directory/file `PROJECT_ROOT/include/header_foo/foo.hpp` and have included `PROJECT_ROOT/include` in the compilation flags, if I include `#include <header_foo/foo.hpp>` in the other headers, it will say that he can't find the file (whereas I'll be able to compile without any problems). It is the same problem when using an external library.

Thank you very much in advance, hoping I was clear enough.

**Comment by jbree** [comment]
Try adding your headers to cmake source list. clangd won't account for include paths to files that are not explicitly specified in compile_commands.json. Annoying, right? There are complaints across the internet about this behavior. I'm not sure if anyone has a good solution yet.

If your issue isn't solved by adding the headers to cmake, there may be another bug here.

**Comment by BigfootN** [comment]
Thank you.

So if I understand well, for the moment it is a "normal" behavior ?

**Comment by NexAdn** [comment]
I found a tool which generates a compile_commands.json from your existing one, but with header files included. One could use this to workaround the problem with the header files: https://github.com/Sarcasm/compdb
