### ISSUE TITLE
Hyperclick root directory path

### ISSUE THREAD

**Issue by C-Bouthoorn** [jbree/ide-clangd#9]
Whenever I ctrl-click on an object in `std::` it jumps to the right file, but under `/include/c++/...` whereas that should be `/usr/include/c++/...` on my system. For now, I've made a softlink between those directories, but it would be nice if you could automatically find the right directory, or add an option where it could be set manually.

**Comment by jbree** [comment]
could you post your compile_commands file?

**Comment by C-Bouthoorn** [comment]
@jbree I haven't used a `compile_commands.json` file for any project so far, and the rest seems to be working fine.

**Comment by jbree** [comment]
An alternative to creating or generating a compile_commands.json would be to use a compile_flags.txt file as mentioned in this issue: https://github.com/jbree/ide-clangd/issues/8

If you make a compile_flags.txt that has a line specifying `-I/usr/include/c++`, that should convince clangd to look in that directory before the other paths it defaults to.

**Comment by C-Bouthoorn** [comment]
For some reason, it seems to work now, even without the `/include` link. Thanks anyhow
